---
name: rust-toolchain
description: "Sets up a standard rust toolchain"
inputs:
  toolchain:
    description: "Which rust toolchain to use"
    required: false
  token:
    description: "Access token for private repos"
    required: false

runs:
  using: "composite"
  steps:
    - id: get-toolchain
      shell: bash
      run: |
        USER_OVERRIDE=${{ inputs.toolchain }}
        DEFAULT_TOOLCHAIN=$(grep channel rust-toolchain.toml | awk '{print $3}' | sed 's/"//g')
        TOOLCHAIN=${USER_OVERRIDE:-$DEFAULT_TOOLCHAIN}
        echo "toolchain=$TOOLCHAIN" >> $GITHUB_OUTPUT
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ steps.get-toolchain.outputs.toolchain }}
        components: rustfmt
    - uses: Swatinem/rust-cache@v2.0.0
      with:
        shared-key: ${{ steps.get-toolchain.outputs.toolchain }}
    - run: git config --global url."https://x-access-token:${{ inputs.token }}@github.com/".insteadOf "https://github.com/"
      if: ${{ inputs.token != null }}
      shell: bash
    - run: git config --global url."https://${{ inputs.token }}@github.com/".insteadOf "git@github.com:"
      if: ${{ inputs.token != null }}
      shell: bash
    - run: git config --global url."https://${{ inputs.token }}@github.com".insteadOf "ssh://git@github.com"
      if: ${{ inputs.token != null }}
      shell: bash
