[[disallowed-methods]]
path = "core::cmp::Ord::min"
reason = '''
Too easy to misread `x.min(y)` as "let the minimum value of `x` be `y`" when it actually means the exact opposite;
Use `std::cmp::min` instead.
'''

[[disallowed-methods]]
path = "core::cmp::Ord::max"
reason = '''
Too easy to misread `x.max(y)` as "let the maximum value of `x` be `y`" when it actually means the exact opposite;
Use `std::cmp::max` instead.
'''
