---
name: ci

on:
  push:
    branches:
      - "**"

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  om-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.CI_READ || github.token }}
          submodules: recursive
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - env:
          CI_READ: ${{ secrets.CI_READ }}
        if: ${{ env.CI_READ != '' }}
        run: |
          git config --global url."https://x-access-token:${CI_READ}@github.com/".insteadOf "git@github.com:"
          git config --global url."https://x-access-token:${CI_READ}@github.com/".insteadOf "https://github.com/"
      - run: nix develop --command om ci
